version: '3'

services:
  php-apache-environment:
    container_name: php-apache
    build:
      context: ./src
      dockerfile: Dockerfile-php
    depends_on:
      - db
    volumes:
      - ./src/embit-backend/embit-dev:/var/www/html/
    ports:
      - 80:80

  composer:
    container_name: composer
    image: composer:latest
    depends_on:
      - php-apache-environment
    volumes:
      - ./src/embit-backend/embit-dev:/var/www/html/
    command: >
      sh -c "cd /var/www/html/ && echo test && ls -l && composer install"

  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: MYSQL_DATABASE
      MYSQL_USER: MYSQL_USER
      MYSQL_PASSWORD: MYSQL_PASSWORD
    ports:
      - "9906:3306"